imports:
  - php
build:
  environment:
    php: '5.6.16'
tools:
  php_code_sniffer:
    filter:
      excluded-paths: [ spec/*, examples/* ]
    config:
      standard: PSR2

  php_analyzer:
    filter:
      excluded-paths: [ spec/*, examples/* ]

  php_sim:
    filter:
      excluded-paths: [ spec/*, examples/* ]

build_failure_conditions:
    - 'issues.label("coding-style").new.exists'

filter:
  paths: [ src/* ]
  excluded_paths:
    - docs/*
    - vendor/*
