---
language: php
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 5.6
  - php: hhvm
  - php: 7.0
  fast_finish: true
before_install:
- |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...${TRAVIS_BRANCH}"
    fi
    IGNORE_LIST='(\.md|rst$)|(LICENSE$)|(\.scrutinizer\.yml$)|(\.(editorconfig|gitignore|gitattributes)$)|(^(docs|examples))/'
    git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE "${IGNORE_LIST}" || {
      echo "No build files updated, stopping build process."
      exit
    }
    if [ "${TRAVIS_PHP_VERSION}" != 'hhvm' ]; then phpenv config-rm xdebug.ini; fi
    composer selfupdate
install:
- export COMPOSER_ROOT_VERSION=dev-master;
- export COMPOSER_NO_INTERACTION=1;
- composer update --prefer-dist --classmap-authoritative;

script:
- bin/phpspec run --format=pretty
...
